### ISSUE TITLE
anyone can eval() python

### ISSUE THREAD

**Issue by ineeee** [icyphox/detotated#1]
*b r u h*,
anyone can run `.eval` and execute python on ur system. should probably stop doing that. cuz, you know, security. irc has some nasty peeps. pls fix. pls. is nasty. kthxbai.

**Comment by icyphox** [comment]
> anyone can run .eval
 
Incorrect. It's anyone on the channel -- which is just Nerdy and I. Also, .eval has been removed for a while now, so I'm not sure why this issue was created, unless of course you didn't bother reading the code. :)

**Comment by icyphox** [comment]
Oh I think I only just removed the function and not the call to the function itself, lol.

**Comment by ineeee** [comment]
besides your invite-only chan, the bot also idles in `#crimbot`, where i managed to crash it by saying `.eval` yesterday. and i did read the code, that's why i found/raised this issue.

seems to be fixed now.
